### ISSUE TITLE
Confirm how to handle .bss segment

### ISSUE THREAD

**Issue by tyfkda** [tyfkda/xv6#19]

**Comment by takeharukato** [comment]
Hi,

First, ELF executables in xv6 does not have a bss segment. 
Although they have a .bss section in its binary containers (ELF), it is included in the first segment in the ELF executable. It might be important to tell the meaning of segments from the meaning of sections in ELF specification correctly. In typical cases, segments should be handled by OS kernels, on the other hand, sections should be handled by language systems.
``` Program headers of /bin/sh in xv6
Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x00000000000000c0 0x0000000000000000 0x0000000000000000
                 0x0000000000001e64 0x0000000000001f08  RWE    20
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RWE    10

 Section to Segment mapping:
  Segment Sections...
   00     .text .rodata .eh_frame .data .bss
   01
```
In addition to this, xv6 kernel provides zeroed-pages to prepare user VMs. 
Thus, xv6 kernel handle .bss section properly.

Would you please pay attention to the fact that exec function copies contents of the segment with ph.filesz NOT ph.memsz.  This is a key trick to make .bss section zeroed because ph.filesz is lesser than 
ph.memsz if .bss section exists. So exec() function can keep pages in  .bss section zero.
``` kernel/exec.c exec() function
    if(loaduvm(pgdir, (char*)ph.vaddr, ip, ph.off, ph.filesz) < 0)
      goto bad;
```
Thanks,
Regards,

**Comment by tyfkda** [comment]
Thank you for your information.
I'll look into the code.
